version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: fallstack23-mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: fallstack23
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
